# Generated by Django 3.1.7 on 2021-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute1', models.CharField(default='John Wick', max_length=200)),
                ('attribute', models.TextField(default='default text')),
            ],
        ),
    ]
